apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        env:
        - name: GCP_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: peer-pods-secret
              key: packer_application_key.json
