apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: peerpodconfig-ctrl-caa-daemon
  namespace: confidential-containers-system
  labels:
    name: peerpodconfig-ctrl-caa-daemon
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: vault-token
      volumes:
        - name: vault-token
          projected:
            sources:
            - serviceAccountToken:
                path: vault-token
                expirationSeconds: 3600
                audience: iam